spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin_route
          uri: lb://azsc-user-directory-service
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin(?<segment>/?.*), /api$\{segment}
        - id: search_route
          uri: lb://azsc-search-directory-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search(?<segment>/?.*), /api$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"