spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin_route
          uri: lb://azsc-user-directory-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin(?<segment>/?.*), $\{segment}
        - id: search_route
          uri: lb://azsc-search-directory-service
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search(?<segment>/?.*), $\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"